Add no pending reports message for pros
betagouv/signalconso-dashboard-react pull request #543
Opened 2024-03-20 16:03 UTC by hakim-sedoud

En tant que professionnel, je veux avoir un message clair lorsque je me connecte et que je n’ai pas de signalement à traiter.

Sur la vue “suivi des signalements à traiter”, lorsqu’aucun signalement n’est en attente de réponse, indiquer clairement :

Aucun signalements

Vous avez répondu à tous vos signalements !

2024-03-20 16:25 UTC, eletallbetagouv requested changes

2024-03-20 16:25 UTC, eletallbetagouv commented on src/core/i18n/localization/fr.ts
> +    noReportsAtAll2Desc: `Vous avez répondu à tous vos signalements !`,
pourquoi "2" dans "noReportsAtAll2Desc" ?

2024-03-20 16:25 UTC, eletallbetagouv commented on src/core/i18n/localization/fr.ts
> +    noReportsAtAll2Desc: `Vous avez répondu à tous vos signalements !`,
Le nouveau message ne convient pas pour la liste des signalements cloturés. Il te faut une troisième variante pour ce cas là.
![Captura de pantalla 2024-03-20 a las 17 25 21](https://github.com/betagouv/signalconso-dashboard-react/assets/107104509/7bbc01a9-a3a4-4209-b726-d34357f917ac)

2024-03-25 09:17 UTC, charlescd commented on src/feature/ReportsPro/ReportsPro.tsx
> +                      icon={'cancel'}
Est-ce que tu peux aussi mettre ça dans `EntityIcon` ?

2024-03-25 11:46 UTC, merged